//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beacon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Beacon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;launchoptions&quot;: [
        ///    {
        ///      &quot;matchmakingregions&quot;: [
        ///        &quot;US-East&quot;,
        ///        &quot;US-Central&quot;,
        ///        &quot;US-West&quot;
        ///      ],
        ///      &quot;gamemodes&quot;: [
        ///        &quot;Defusal&quot;,
        ///        &quot;Hostage Rescue&quot;
        ///      ],
        ///      &quot;maps&quot;: {
        ///        &quot;gamemaps0&quot;: [
        ///          &quot;Aztec&quot;,
        ///          &quot;Cbble&quot;,
        ///          &quot;Chateau&quot;,
        ///          &quot;Dust&quot;,
        ///          &quot;Dust2&quot;,
        ///          &quot;Piranesi&quot;,
        ///          &quot;Prodigy&quot;,
        ///          &quot;Tides&quot;,
        ///          &quot;Train&quot;,
        ///          &quot;Inferno&quot;,
        ///          &quot;Port&quot;,
        ///          &quot;Nuke&quot;
        ///        ],
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string counterstrikesource {
            get {
                return ResourceManager.GetString("counterstrikesource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap header_counterstrikesource {
            get {
                object obj = ResourceManager.GetObject("header_counterstrikesource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap header_teamfortress2 {
            get {
                object obj = ResourceManager.GetObject("header_teamfortress2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;launchoptions&quot;: [
        ///    {
        ///      &quot;matchmakingregions&quot;: [
        ///        &quot;US-East&quot;,
        ///        &quot;US-Central&quot;,
        ///        &quot;US-West&quot;
        ///      ],
        ///      &quot;gamemodes&quot;: [
        ///        &quot;Attack &amp; Defend&quot;,
        ///        &quot;Control Points&quot;,
        ///        &quot;King of the Hill&quot;,
        ///        &quot;Payload&quot;,
        ///        &quot;Capture the Flag&quot;
        ///      ],
        ///      &quot;connections&quot;: [
        ///        &quot;ctf_2fort&quot;,
        ///        &quot;koth_harvest&quot;,
        ///        &quot;pl_upward&quot;,
        ///        &quot;cp_well&quot;,
        ///        &quot;cp_dustbowl&quot;
        ///      ] 
        ///    }
        ///  ]
        ///}
        ///.
        /// </summary>
        public static string teamfortress2 {
            get {
                return ResourceManager.GetString("teamfortress2", resourceCulture);
            }
        }
    }
}
